name: deploy
on:
  push:
    branches:
      - husk
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # would like to husk and push to new branch and deploy that
      - uses: bcomnes/deploy-to-neocities@v3.0.2
        with:
          api_key: ${{ secrets.NEOCITIES }}
          cleanup: true
          dist_dir: src
      - uses: indiefellas/deploy2nekoweb@v1.0.0
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB }}
          nekoweb-domain: spuds.nekoweb.org
          nekoweb-username: spuds
          # for some reason you can't zip . with this action
          directory: src