name: husk
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - uses: actions/deploy-pages@v4
  husk:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v6
    - id: changed
      uses: tj-actions/changed-files@v47.0.1
      with:
        files: '*.html'
        diff_relative: 'false'
    - uses: actions/checkout@v6
      with:
        ref: husk
    - run: |
        changed="${{ steps.changed.outputs.all_changed_files }}"
        if test -n "$changed"; then
          IFS=' ' read -a split <<< "$changed"
          for file in "${split[@]}"; do
            if ["${file##*.}" != "html"]; then
              echo "$file"
              continue
            fi
            echo "$file"
            moved="src/$file"
            echo "<!DOCTYPE html>" > $moved
            echo "<head>" >> $moved
            echo "  <meta http-equiv=\"refresh\" content=\"0; url=https://spuds.casa/$file\">" >> $moved
            echo "</head>" >> $moved
            echo "<!-- ${{ github.sha }} -->" >> $moved
            echo "</html>" >> $moved
          done
        fi
    - uses: EndBug/add-and-commit@v9.1.4
  deploy-husk:
    # wait for deploy to finish so that thumbnails are correct
    needs: [deploy, husk]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: husk
    - uses: bcomnes/deploy-to-neocities@v3.0.2
      with:
        api_key: ${{ secrets.NEOCITIES }}
        cleanup: true
        dist_dir: src
    - uses: indiefellas/deploy2nekoweb@v1.0.0
      with:
        nekoweb-api-key: ${{ secrets.NEKOWEB }}
        nekoweb-domain: spuds.nekoweb.org
        nekoweb-username: spuds
        # for some reason you can't zip . with this action
        directory: src
